import 'controller/search_seven_controller.dart';import 'package:flutter/material.dart';import 'package:talextra/core/app_export.dart';import 'package:talextra/widgets/app_bar/appbar_image.dart';import 'package:talextra/widgets/app_bar/appbar_title.dart';import 'package:talextra/widgets/app_bar/custom_app_bar.dart';class SearchSevenScreen extends GetWidget<SearchSevenController> {const SearchSevenScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.black900, appBar: CustomAppBar(height: getVerticalSize(109), centerTitle: true, title: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 28, right: 29), child: Row(children: [AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowleftPink50, margin: getMargin(top: 8, bottom: 8), onTap: () {onTapArrowleft13();}), AppbarTitle(text: "lbl_contact_option2".tr, margin: getMargin(left: 15, top: 5, bottom: 4)), AppbarImage(height: getSize(40), width: getSize(40), svgPath: ImageConstant.imgCirclecheckicondefault, margin: getMargin(left: 106), onTap: () {onTapCirclecheckicon3();})])), Padding(padding: getPadding(top: 25), child: SizedBox(width: double.maxFinite, child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.deepOrangeA200.withOpacity(0.5))))]), styleType: Style.bgFill_1), body: Container(width: double.maxFinite, padding: getPadding(left: 25, top: 33, right: 25, bottom: 33), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("msg_public_information".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleMediumPrimary18), Padding(padding: getPadding(left: 12, top: 25), child: Row(children: [CustomImageView(svgPath: ImageConstant.imgMailOnprimary, height: getSize(24), width: getSize(24)), Padding(padding: getPadding(left: 17, top: 2), child: Text("msg_megastallion_gmail_com".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.bodyLarge))])), Align(alignment: Alignment.center, child: Padding(padding: getPadding(left: 15, top: 29), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgCall, height: getSize(24), width: getSize(24)), Padding(padding: getPadding(left: 15, bottom: 1), child: Text("msg_234_814_258_6677".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.bodyLarge)), Spacer(), CustomImageView(svgPath: ImageConstant.imgArrowleftOnprimary, height: getSize(24), width: getSize(24))]))), Padding(padding: getPadding(top: 58), child: Text("msg_display_contact".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.titleMediumPrimary18)), Container(width: getHorizontalSize(360), margin: getMargin(top: 13, right: 17, bottom: 5), child: Text("msg_showing_your_contact".tr, maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: CustomTextStyles.bodyMediumOnPrimaryLight))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleft13() { Get.back(); } 
/// Navigates to the searchEightScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the searchEightScreen.
onTapCirclecheckicon3() { Get.toNamed(AppRoutes.searchEightScreen, ); } 
 }
