import '../search_one_screen/widgets/search_one_item_widget.dart';import 'controller/search_one_controller.dart';import 'models/search_one_item_model.dart';import 'package:flutter/material.dart';import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';import 'package:talextra/core/app_export.dart';import 'package:talextra/presentation/geo_discovery_page/geo_discovery_page.dart';import 'package:talextra/presentation/search_nine_page/search_nine_page.dart';import 'package:talextra/presentation/search_page/search_page.dart';import 'package:talextra/presentation/search_three_page/search_three_page.dart';import 'package:talextra/presentation/wallet_page/wallet_page.dart';import 'package:talextra/widgets/app_bar/appbar_image.dart';import 'package:talextra/widgets/app_bar/appbar_title.dart';import 'package:talextra/widgets/app_bar/custom_app_bar.dart';import 'package:talextra/widgets/custom_bottom_bar.dart';class SearchOneScreen extends GetWidget<SearchOneController> {const SearchOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.black900, appBar: CustomAppBar(height: getVerticalSize(108), leadingWidth: 61, leading: AppbarImage(height: getSize(40), width: getSize(40), svgPath: ImageConstant.imgCirclecloseiconwhite, margin: getMargin(left: 21, top: 34, bottom: 34), onTap: () {onTapCirclecloseicon();}), title: AppbarTitle(text: "lbl_new_post".tr, margin: getMargin(left: 19)), actions: [AppbarImage(height: getSize(40), width: getSize(40), svgPath: ImageConstant.imgCirclecheckicondefault, margin: getMargin(left: 25, top: 34, right: 25, bottom: 34), onTap: () {onTapCirclecheckicon();})], styleType: Style.bgFill), body: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: appTheme.deepOrangeA200.withOpacity(0.5)), Spacer(), CustomImageView(imagePath: ImageConstant.imgRectangle1471, height: getVerticalSize(31), width: getHorizontalSize(428)), Expanded(child: Padding(padding: getPadding(bottom: 6), child: Obx(() => StaggeredGridView.countBuilder(shrinkWrap: true, primary: false, crossAxisCount: 6, crossAxisSpacing: getHorizontalSize(6), mainAxisSpacing: getHorizontalSize(6), staggeredTileBuilder: (index) {return StaggeredTile.fit(2);}, itemCount: controller.searchOneModelObj.value.searchOneItemList.value.length, itemBuilder: (context, index) {SearchOneItemModel model = controller.searchOneModelObj.value.searchOneItemList.value[index]; return SearchOneItemWidget(model);}))))])), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.walletPage; case BottomBarEnum.Mapicon: return AppRoutes.geoDiscoveryPage; case BottomBarEnum.Searchicon: return AppRoutes.searchPage; case BottomBarEnum.Usergroupicon: return AppRoutes.searchNinePage; case BottomBarEnum.Useraddicon: return AppRoutes.searchThreePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.walletPage: return WalletPage(); case AppRoutes.geoDiscoveryPage: return GeoDiscoveryPage(); case AppRoutes.searchPage: return SearchPage(); case AppRoutes.searchNinePage: return SearchNinePage(); case AppRoutes.searchThreePage: return SearchThreePage(); default: return DefaultWidget();} } 
/// Navigates to the dashboardScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the dashboardScreen.
onTapCirclecloseicon() { Get.toNamed(AppRoutes.dashboardScreen, ); } 
/// Navigates to the searchEightScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the searchEightScreen.
onTapCirclecheckicon() { Get.toNamed(AppRoutes.searchEightScreen, ); } 
 }
