import '../select_interest_screen/widgets/select_interest_item_widget.dart';import 'controller/select_interest_controller.dart';import 'models/select_interest_item_model.dart';import 'package:flutter/material.dart';import 'package:talextra/core/app_export.dart';import 'package:talextra/widgets/app_bar/appbar_image.dart';import 'package:talextra/widgets/app_bar/custom_app_bar.dart';import 'package:talextra/widgets/custom_elevated_button.dart';class SelectInterestScreen extends GetWidget<SelectInterestController> {const SelectInterestScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.black900, appBar: CustomAppBar(height: getVerticalSize(79), leadingWidth: 44, leading: AppbarImage(height: getSize(24), width: getSize(24), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 20, top: 16, bottom: 15), onTap: () {onTapArrowleft4();}), centerTitle: true, title: Text("lbl_select_interest".tr.toUpperCase(), overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: theme.textTheme.titleLarge!.copyWith(letterSpacing: getHorizontalSize(4.0)))), body: Container(width: double.maxFinite, padding: getPadding(left: 17, top: 41, right: 17, bottom: 41), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgUseraddiconPrimary, height: getSize(24), width: getSize(24)), Container(height: getSize(5), width: getSize(5), margin: getMargin(left: 27, top: 10, bottom: 9), decoration: BoxDecoration(color: appTheme.blueGray400, borderRadius: BorderRadius.circular(getHorizontalSize(2)))), CustomImageView(svgPath: ImageConstant.imgUseraddiconPrimary24x24, height: getSize(24), width: getSize(24), margin: getMargin(left: 18)), Container(height: getSize(5), width: getSize(5), margin: getMargin(left: 19, top: 10, bottom: 9), decoration: BoxDecoration(color: appTheme.blueGray400, borderRadius: BorderRadius.circular(getHorizontalSize(2)))), CustomImageView(svgPath: ImageConstant.imgPhotoicon, height: getSize(24), width: getSize(24), margin: getMargin(left: 18))]), Container(width: getHorizontalSize(192), margin: getMargin(top: 32), child: Text("msg_select_categories".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.labelLarge)), Expanded(child: Padding(padding: getPadding(left: 8, top: 29, right: 6), child: Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(83), crossAxisCount: 4, mainAxisSpacing: getHorizontalSize(16), crossAxisSpacing: getHorizontalSize(16)), physics: NeverScrollableScrollPhysics(), itemCount: controller.selectInterestModelObj.value.selectInterestItemList.value.length, itemBuilder: (context, index) {SelectInterestItemModel model = controller.selectInterestModelObj.value.selectInterestItemList.value[index]; return SelectInterestItemWidget(model);})))), CustomElevatedButton(text: "lbl_get_started".tr, margin: getMargin(top: 55, bottom: 5), buttonStyle: CustomButtonStyles.fillPrimary.copyWith(fixedSize: MaterialStateProperty.all<Size>(Size(double.maxFinite, getVerticalSize(48)))), buttonTextStyle: theme.textTheme.titleMedium!, onTap: () {onTapGetstarted();})])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleft4() { Get.back(); } 
/// Navigates to the dashboardScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the dashboardScreen.
onTapGetstarted() { Get.toNamed(AppRoutes.dashboardScreen, ); } 
 }
